In [124]:
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import os, sys
import pandas as pd 
from sklearn.metrics.pairwise import cosine_similarity

import torch

In [125]:
def cos_sim(input_vectors):
    similarity = cosine_similarity(input_vectors)
    return similarity

In [126]:
def manhattan_distance(x,y):
    return sum(abs(a-b) for a,b in zip(x,y))

In [127]:
def jaccard_similarity(x,y):
    intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
    union_cardinality = len(set.union(*[set(x), set(y)]))
    return intersection_cardinality/float(union_cardinality)

In [128]:
def get_top_similar(sentence, sentence_list, similarity_matrix, topN):
    # find the index of sentence in list
    index = sentence_list.index(sentence)
    # get the corresponding row in similarity matrix
    similarity_row = np.array(similarity_matrix[index, :])
    # get the indices of top similar
    indices = similarity_row.argsort()[-topN:][::-1]
    return [sentence_list[i] for i in indices]

In [129]:
%%time
embed = hub.load("D:/USE",)

Wall time: 20 s


In [130]:
sentences_list = [
#     # phone related
#     'My phone is slow',
#     'My phone is not good',
#     'I need to change my phone. It does not work well',
#     'How is your phone?',

#     # age related
#     'What is your age?',
#     'How old are you?',
#     'I am 10 years old',

#     # weather related
#     'It is raining today',
#     'Would it be sunny tomorrow?',
#     'The summers are here.
    
    ## Negation case 
    
    ## WMD Case 
    "Obama speaks to the media in Illinois" ,
    "The President greets the press in Chicago"
]


In [131]:
sentences_embeddings = embed(sentences_list)

In [132]:
sentences_embeddings 

<tf.Tensor: shape=(2, 512), dtype=float32, numpy=
array([[ 0.05702654,  0.00514278, -0.00563831, ...,  0.04052125,
        -0.04780073,  0.01507273],
       [ 0.06268193,  0.02098889,  0.01350735, ...,  0.01703019,
        -0.02913601,  0.03807865]], dtype=float32)>

In [133]:
np.array(sentences_embeddings)

array([[ 0.05702654,  0.00514278, -0.00563831, ...,  0.04052125,
        -0.04780073,  0.01507273],
       [ 0.06268193,  0.02098889,  0.01350735, ...,  0.01703019,
        -0.02913601,  0.03807865]], dtype=float32)

In [134]:
similarity_matrix = cos_sim(np.array(sentences_embeddings))

In [135]:
similarity_matrix_df = pd.DataFrame(similarity_matrix) 

In [136]:
similarity_matrix_df

0        1
0  1.00000  0.53683
1  0.53683  1.00000

In [137]:
arr = np.array(sentences_embeddings)
print(manhattan_distance(arr[0],arr[1]))

17.06541581870988


In [138]:
arr1 = np.array(sentences_embeddings)
print(jaccard_similarity(arr[0],arr[1]))

0.0


In [139]:
cosine_similarity(arr1)

array([[1.0000002, 0.5368296],
       [0.5368296, 1.0000001]], dtype=float32)

## Trying USE in BERT  